
# Arc Blueberry Alacritty Colors
# Derived from BeardedTheme Arc-blueberry VS Code theme
[colors.primary]
background = '#0f121e'
foreground = '#bcc1dc'

[colors.normal]
black = '#111422'
red = '#E35535'
green = '#3CEC85'
yellow = '#EACD61'
blue = '#69C3FF'
magenta = '#F38CEC'
cyan = '#22ECDB'
white = '#bcc1dc'


[colors.bright]
black = '#313b62'
red = '#ff4319'
green = '#29ff82'
yellow = '#ffd94c'
blue = '#69c3ff'
magenta = '#ff80f6'
cyan = '#0fffeb'
white = '#ffffff'

[colors.cursor]
cursor = '#EACD61'
text = '#0f121e'

[colors.selection]
text = '#ffffff'
background = '#222844'

# Indexed Colors - Mapped to Arc Blueberry's main blue and red
[[colors.indexed_colors]]
index = 16
color = '#69C3FF' # Arc Blueberry Blue

[[colors.indexed_colors]]
index = 17
color = '#E35535' # Arc Blueberry Red
[terminal.shell]
program = "C:\\windows\\system32\\wsl.exe"
args = ["--cd ~"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 18
#for full screen it's Alt + Enter

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
decorations = "full"

[scrolling]
history = 0

[general]
live_config_reload = true

[terminal]

[window.padding]
x = 15
y = 15
